config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :reviews do
    resources :likes, only: [:create, :destroy]
  end
  
  resources :users
  resources :reviews, expect: [:index]
  resources :vehicles

  get 'likes/create'
  get 'likes/destroy'

  get '/reviews/:user_id/index', to: 'reviews#index'
  get '/search', to: 'home#search'

  get '/makers', to: 'makers#index'
  get '/makers_ve', to: 'makers#vehicle_form'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  include Admin_common

  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :correct_user_check, only: [:edit, :update, :destroy]
  
  def new
    @vehicle = Vehicle.find_by(id: params[:vehicle_id])
    @maker = Maker.find(@vehicle.maker_id)
    @path = Rails.application.routes.recognize_path(request.referer)

    error_message = Review.duplicate_review(@current_user.id, @vehicle.id)
    if error_message
      if @path[:controller] == "vehicles"
        redirect_to vehicle_path(@vehicle.id), alert: error_message 
      else
        redirect_to makers_path, alert: error_message
      end
    end
    @review = Review.new
  end

  def edit
  end

  def update
    if params[:image]
      @review.image.attach(params[:review][:image])
    end

    if @review.update(review_params)
      redirect_to "/reviews/#{@current_user.id}/index", notice: "レビュー「#{@review.title}」を更新しました。"
    else
      render :edit
    end
  end

  def create
    @vehicle = Vehicle.find_by(id: params[:vehicle_id])
    @review = @current_user.reviews.new(review_params.merge(vehicle_id: @vehicle.id))

    if @review.save
      redirect_to "/reviews/#{@current_user.id}/index", notice: "レビュー「#{@review.title}」を登録しました。"
    else
      @path = Rails.application.routes.recognize_path(request.referer)
      render :new
    end
  end

  def destroy
    @review.destroy
    unless request.xhr?
      redirect_to "/reviews/#{@current_user.id}/index", notice: "レビュー「#{@review.title}」を削除しました。"
    end
  end

  def show
    # 遷移元のcontroller,actionを取得
    @path = Rails.application.routes.recognize_path(request.referer)
  end

  def index
    search_by_ransack
  end

  private

  def set_review
    @review = Review.find(params[:id])
    @vehicle = Vehicle.find(@review.vehicle_id)
  end

  def review_params
    params.require(:review).permit(:title, :body, :image)
  end

  def correct_user_check
    redirect_to root_path, notice: "権限がありません" unless @current_user.id == @review.user.id
  end

  def search_by_ransack
    @user = User.find_by(id: params[:user_id])
    @q = @user.reviews.includes(:vehicle).ransack(params[:q])
    @reviews = @q.result(distinct: true).page(params[:page]).per(Review::REVIEWLIST_PAGINATION_MAX)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/shared/reviews/_index.html.slim
= form_with url: search_path, local: true, method: 'get', class: 'search-form' do
  .form-group-search
    = search_field_tag :search, '', class: 'form-control'
  = submit_tag '検索', class: 'btn btn-primary btn-search'

= render partial: 'shared/reviews/reviewlist', locals: { reviews: reviews }


app/views/shared/reviews/_reviewlist.html.slim
- if reviews.present?
  .home-shared-review-list
    - reviews.each do |review|
      .shared-review-list
        .item.user-avatar
          = link_to user_path(review.user) do
            = user_image(review.user, 'trim-image-to-circle')

            .likes-button
              div id="likes_buttons_#{review.id}"
                = render partial: 'likes/like', locals: { review: review, likes: @likes }
        .item.item-list
          .item.user-name
            = link_to review.user.name.truncate(20), user_path(review.user), class: 'review-user-name'
            = "・" + I18n.l(review.created_at, format: :short)
          .item.vehicle-title-body
            .item.vehicle-name
              = link_to "【#{review.vehicle.name}】", vehicle_path(review.vehicle.id)
              = link_to review.title, review_path(review), class: 'title'
            .item.title-body
              = link_to "", review_path(review), class: 'link-body'
              = review.body.truncate(105)

  .paginate-reviews
    .paginate-reviews-info
      = page_entries_info reviews
    = paginate reviews

- else
  p レビュー投稿はありません。