config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :reviews do
    resources :likes, only: [:create, :destroy]
  end
  
  resources :users
  resources :reviews, expect: [:index]
  resources :vehicles

  get 'likes/create'
  get 'likes/destroy'

  get '/reviews/:user_id/index', to: 'reviews#index'
  get '/search', to: 'home#search'

  get '/makers', to: 'makers#index'
  get '/makers_ve', to: 'makers#vehicle_form'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one_attached :avatar

  has_many :reviews, dependent: :destroy
  has_many :vehicles, through: :reviews

  DEFAULT_AVATER = "default_avater.jpg"

  validates :name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end

  def thumbnail
    return self.avatar.variant(resize: '600x600').processed
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include Admin_common

  before_action :require_admin, only: [:index, :destroy]
  before_action :correct_user_check, only: [:edit, :update]

  skip_before_action :login_required, only: [:new, :create]
 
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @likes = Like.likes(params[:page], @user)
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      if cookies[:user_remember_token]
        redirect_to users_path, notice: "ユーザ「#{@user.name}」を登録しました。"
      else
        # セッションが存在しない場合、新規登録と見なしてrootに遷移する
        sign_in(@user)
        redirect_to root_path, notice: "ユーザ「#{@user.name}」を登録しました。"
      end
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if params[:avatar]
      @user.avatar.attach(params[:user][:avatar])
    end

    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "ユーザ「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: "ユーザ「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmaiton, :avatar)
  end

  def correct_user_check
    redirect_to root_path, alert: "権限がありません" unless @current_user.id == params[:id].to_i
  end
 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
     - user.errors.full_messages.each do |message|
       li= message

= form_with model: @user, local: true do |f|
  .form-group
     = f.label :name, '名前'
     = f.text_field :name, class: 'form-control'
  .form-group
     = f.label :email, 'メールアドレス'
     = f.email_field :email, class: 'form-control'
  .form-group
    = f.label :avatar
    = f.file_field :avatar, class: 'form-control'
  .form-group
     = f.label :password, 'パスワード'
     = f.password_field :password, class: 'form-control'
  .form-group
     = f.label :password_confirmation, 'パスワード（確認）'
     = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/users/edit.html.slim
h1 プロフィール編集

.nav.justify-content-end

=render partial: 'form', locals: { user: @user}

app/views/users/index.html.slim
h1 ユーザ一覧

= link_to '新規登録', new_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:admin)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td= link_to user.name, user
        td= user.email
        td= user.admin? ?  'あり' : 'なし'
        td= user.created_at.to_s(:db)
        td= user.updated_at.to_s(:db)
        td
          = link_to '編集', edit_user_path(user), class: 'btn btn-primary mr-3'
          = link_to '削除', user, method: :delete, data: { confirm: "ユーザ「#{user.name}」を削除します。よろしいですか？投稿も自動で削除されます。"}, class: 'btn btn-danger'

app/views/users/new.html.slim
h1 ユーザ登録

.nav.justify-content-end
  - if current_user
    = link_to '一覧', users_path, class: 'nav-link'

=render partial: 'form', locals: { user: @user}

app/views/users/show.html.slim
.row
  .col-md-3
    .myhome-top
      = user_image(@user, 'avatar-to-circle')
      p.user-name= @user.name
      ul.sub-menu
        - if correct_user(@user.id)
          li= link_to 'プロフィール設定', edit_user_path(current_user)
        li= link_to '投稿一覧', "/reviews/#{@user.id}/index"
  .col-md-9
.row
  .col-md-10
    h3.notification 通知
    .likes-list
      - @likes.each do |like|
        .like
          = link_to user_path(like.user) do
            = user_image(like.user, 'like-avatar-to-circle')
          = link_to like.user.name.truncate(10), user_path(like.user), class: 'like-user-name'
          span が
          = link_to like.review.title.truncate(15), review_path(like.review), class: 'like-review-title'
          span に「参考になった」をしました
          = "・" + I18n.l(like.created_at, format: :short)

    .paginate-like
    .paginate-like-info
      = page_entries_info @likes
    = paginate @likes