config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :reviews do
    resources :likes, only: [:create, :destroy]
  end
  
  resources :users
  resources :reviews, expect: [:index]
  resources :vehicles

  get 'likes/create'
  get 'likes/destroy'

  get '/reviews/:user_id/index', to: 'reviews#index'
  get '/search', to: 'home#search'

  get '/makers', to: 'makers#index'
  get '/makers_ve', to: 'makers#vehicle_form'
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :maker
  has_many :reviews, dependent: :restrict_with_error
  has_many :users, through: :reviews

  validates :name, presence: true

  NO_IMAGE_PATH = "vehicles/no-image.png"

  scope :name_order_asc , -> { order(name: "ASC") }

  def self.ransackable_attributes(auth_object = nil)
    %w[name]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  def image?
    File.exist? "#{Rails.root}/app/assets/images/vehicles/#{self.id}.jpg"
  end

  def image_path
    "vehicles/#{self.id}.jpg"
  end

  def movie_split
    self.movie.split(',')
  end

  def maker
    Maker.find_by(id: self.maker_id)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  include Admin_common
  before_action :require_admin, except: [:index, :show]

  before_action :set_vehicle, {only: [:show, :edit, :update, :destroy]}
  
  def index
    @vehicles = Vehicle.all.name_order_asc
  end

  def new
    @vehicle = Vehicle.new
    @makers = Maker.all.order_asc
  end

  def show
    @maker = Maker.find(@vehicle.maker_id)
    @reviews = Review.search(params[:page], vehicle_id: @vehicle.id)
  end

  def edit
    @makers = Maker.all.order_asc
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)

    if @vehicle.save
      @vehicle.reload
      
      save_image

      redirect_to vehicles_path, notice: "「#{@vehicle.name}」を登録しました。"
    else
      @makers = Maker.all.order_asc
      flash[:notice] = "「#{@vehicle.name}」を登録できませんでした。"
      render :new
    end
  end

  def update
    save_image

    if @vehicle.update(vehicle_params)
      redirect_to vehicle_path(@vehicle), notice: "「#{@vehicle.name}」を更新しました。"
    else
      flash[:notice] = "「#{@vehicle.name}」を更新できませんでした。"
      render :new
    end
  end

  def destroy
    # 既に投稿されていた場合、削除できない
    if @vehicle.destroy
      redirect_to vehicles_url, notice: "「#{@vehicle.name}」を削除しました。"
    else
      redirect_to vehicles_url, alert: "「#{@vehicle.name}」を削除できませんでした。既に投稿されています。"
    end
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:name, :maker_id, :movie)
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def fileupload_param
    params.require(:fileupload).permit(:file)
  end

  def save_image
    if params[:fileupload] && fileupload_param[:file]
      uploaded_file = fileupload_param[:file]
      image_name = "#{@vehicle.id}.jpg"
      File.binwrite("app/assets/images/vehicles/#{image_name}", uploaded_file.read)
    end
  end

end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.slim
- if vehicle.errors.present?
  ul#error_explanation
     - vehicle.errors.full_messages.each do |message|
       li= message

= form_with model: @vehicle, local: true, multipart: true do |f|
  .form-group
    = f.label Maker.human_attribute_name(:name)
    .makers-check
      - @makers.each do |maker|
        .form-check-inline
          - if maker.id == 1
            f.= radio_button_tag :maker_id, maker.id, true, id: maker.name, class: 'form-check-input'
          - else
            f.= radio_button_tag :maker_id, maker.id, false, id: maker.name, class: 'form-check-input'
          = f.label :maker_name, maker.name, for: maker.name, class: 'form-check-label'
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :image, 'イメージ'
    = file_field :fileupload, :file, accept: 'image/jpg', class: 'form-control'
  .form-group
    = f.label :movie
    = f.label "（VIDEO_IDをカンマ区切りで指定）"
    = f.text_field :movie, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/vehicles/edit.html.slim
h1 車両の編集

.nav.justify-content-end
  = link_to '一覧', vehicles_path, class: 'nav-link'

=render partial: 'form', locals: { vehicle: @vehicle}

app/views/vehicles/index.html.slim
h1 車両一覧

- if current_user.admin?
  = link_to '新規登録', new_vehicle_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Vehicle.human_attribute_name(:name)
      th= Maker.human_attribute_name(:name)
      th
  tbody
    - @vehicles.each do |vehicle|
      tr
        td= link_to vehicle.name, vehicle
        td= vehicle.maker.name
        td
          - if current_user.admin?
            = link_to '編集', edit_vehicle_path(vehicle), class: 'btn btn-primary mr-3'
            = link_to '削除', vehicle, method: :delete, remote: true, data: { confirm: "「#{vehicle.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger delete'

app/views/vehicles/new.html.slim
h1 車両登録

.nav.justify-content-end
  = link_to '一覧', vehicles_path, class: 'nav-link'

=render partial: 'form', locals: { vehicle: @vehicle }

app/views/vehicles/show.html.slim
h1 車両詳細

.nav.justify-content-end
  = link_to '一覧', vehicles_path, class: 'nav-link'

= link_to 'レビューを書く', new_review_path(vehicle_id: @vehicle.id), class: 'btn btn-primary write-review'

table.table.table-hover
  tbody
    - if current_user.admin?
      tr
        th= Vehicle.human_attribute_name(:id)
        td= @vehicle.id
    tr
      th= Vehicle.human_attribute_name(:name)
      td= @vehicle.name
    tr
      th= Maker.human_attribute_name(:name)
      td= @maker.name
    tr
      th= Review.human_attribute_name(:image)
      td= vehicle_image(@vehicle, 'form-vehicle-image')

- if current_user.admin?
  = link_to '編集', edit_vehicle_path, class: 'btn btn-primary mr-3'
  = link_to '削除', @vehicle, method: :delete, data: { confirm: "「#{@vehicle.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

p.reviews-heading レビュー一覧
= render partial: 'shared/reviews/reviewlist', locals: { reviews: @reviews }

p.review-movies-heading =Vehicle.human_attribute_name(:movie)
- if @vehicle.movie.nil?
  p =Vehicle.human_attribute_name(:movie) + 'はありません。'
- else
  - @vehicle.movie_split.each do |movie|
    .review-movie
      = movie(movie_id: movie)