config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :reviews do
    resources :likes, only: [:create, :destroy]
  end
  
  resources :users
  resources :reviews, expect: [:index]
  resources :vehicles

  get 'likes/create'
  get 'likes/destroy'

  get '/reviews/:user_id/index', to: 'reviews#index'
  get '/search', to: 'home#search'

  get '/makers', to: 'makers#index'
  get '/makers_ve', to: 'makers#vehicle_form'
end

app/views/layouts/_footer.html.slim
.container.footer__container
  ul.footer_links-left
    li.footer_link= link_to '© 2019 Komatsu Inc.', '#'
    li.footer_link= link_to '利用規約', '#'
    li.footer_link= link_to 'ガイドライン', '#'
    li.footer_link= link_to 'プライバシー', '#'
    li.footer_link= link_to 'ヘルプ', '#'

app/views/layouts/_navigation.html.slim
.app-title.navbar.navbar-expand-md.navbar-dark.bg-primary.sticky-top
  = link_to 'Motoprize', root_path, class: 'navbar-brand'
  .ul.navbar-nav.mr-auto
    - if current_user
      li.nav-item= link_to 'ホーム', root_path, class: 'nav-link'
      li.nav-item= link_to 'マイページ', user_path(current_user), class: 'nav-link'
      li.nav-item= link_to '新規投稿', makers_path, class: 'nav-link'
      - if current_user.admin?
        li.nav-item= link_to 'ユーザ一覧', users_path, class: 'nav-link'
      li.nav-item= link_to '車両一覧', vehicles_path, class: 'nav-link'
      li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
    - else
      li.nav-item= link_to '新規登録', new_user_path, class: 'nav-link'
      li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
    - if current_user
      = link_to current_user.name.truncate(12) + "さん", user_path(current_user), class: 'navbar-brand current-user-name'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Motoprize
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag('bike.png')
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'https://fonts.googleapis.com/icon?family=Material+Icons'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
  body
    header
      = render 'layouts/navigation'
    .wrapper
      .container
        / RSpecにてtoastrのテストは難しいためtest環境は通常のflashを使用する
        - if Rails.env.test?
          - if flash.notice.present?
            .alert.alert-success= flash.notice
        - else
          - flash.each do |type, msg|
            - type = 'info' if type == 'notice'
            - type = 'error' if type == 'alert'
            javascript:
              toastr["#{type}"]("#{msg}");

        = yield
      footer
        = render 'layouts/footer'